### ISSUE TITLE
[Button]centralize

### ISSUE THREAD

**Issue by sleepy-maker** [Lenordchen/Fingerprint-#1]
try this for the button
i don't remember the id name you use for the button. so you need to the nema(after `#`)

```css
#button {
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%,-50%);
  -webkit-transform : translate(-50%,-50%);
  transform : translate(-50%,-50%);
}
```
